# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h1xARpjQ0LVVNMS3D_nJxOWl92kR4Z3u
"""

#pip install twilio

import os
from twilio.rest import Client
import re

account_sid = "ACc477c36d89ee5df0d644f9fe57de0369"
auth_token = "2d895fcadede19d01fdd73d4aa19f7df"
client = Client(account_sid, auth_token)




def get_email():
  # code to get email from field
  email = input("Enter email:")
  return email

def get_code():
  # code to get otp from field
  code = input("Enter code:")
  return code

def verification(email):
  verification = client.verify \
                     .v2 \
                     .services('VAd9044e73fa8ffe49d8eb2abb6e8a8f24') \
                     .verifications \
                     .create(to=email, channel='email')


def verification_check(email,code):
  verification_check = client.verify \
                           .v2 \
                           .services('VAd9044e73fa8ffe49d8eb2abb6e8a8f24') \
                           .verification_checks \
                           .create(to=email, code=code)
  return verification_check.status

email = get_email()
if(bool(re.match(r"^[A-Za-z0-9._%+-]+@umass\.edu$", email))):
  verification(email)
  status = verification_check(email,get_code())
  print(status)
