# -*- coding: utf-8 -*-
"""Visualization.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uXZML7q2zW2p6-g_0Lf8VsHZgfFm2QOB
"""

import pandas as pd
import plotly.graph_objects as go

data = {'Average Hours Spent': [1,2,3,5,7,20], "Difficulty": [1,3,4,5,2,1]}

df = pd.DataFrame(data=data)

fig = go.Figure()

fig.add_trace(go.Histogram(x=df["Average Hours Spent"],name = "Average Hours Spent",marker=dict(color="Crimson"),xbins=dict(start=0, size=1, end=40),opacity = 0.75))
fig.add_trace(go.Histogram(x=df["Difficulty"],nbinsx=5,name="Difficulty of the course",marker=dict(color="RebeccaPurple"),xbins=dict(start=0, size=1, end=5),opacity = 0.75))

    
fig.update_layout(
    updatemenus=[go.layout.Updatemenu(
        active=0,
        buttons=list(
            [dict(label = 'Average Hours Spent per week',
                  method = 'update',
                  args = [{'visible': [True, False]},
                          {'title': 'Average Hours Spent per week',
                           'showlegend':True
                           }]),
             dict(label = 'Difficulty level of the course',
                  method = 'update',
                  args = [{'visible': [False, True]}, # the index of True aligns with the indices of plot traces
                          {'title': 'Difficulty level of the course',
                           'showlegend':True
                           }]),
            ])
        )
    ])
fig.show()
fig.write_html('Course Load and Difficulty')
